import fs from 'fs';
import path from 'path';
import { format } from 'date-fns';
import { LinkedInPost } from './collector';

export class Generator {
    async createNewsletter(summary: string, posts: LinkedInPost[]) {
        const dateStr = format(new Date(), 'yyyy-MM-dd');
        const filename = `newsletter_${dateStr}.md`;
        const outputPath = path.join(process.cwd(), 'output');

        if (!fs.existsSync(outputPath)) {
            fs.mkdirSync(outputPath);
        }

        const content = `
# Daily AI LinkedIn Newsletter - ${dateStr}

${summary}

## Source Posts
${posts.map(p => `- [${p.title}](${p.link})\n  > ${p.snippet.replace(/\n/g, ' ')}`).join('\n')}

---
Generated by SocialMediaCollationforAI
`.trim();

        fs.writeFileSync(path.join(outputPath, filename), content);
        console.log(`✅ Newsletter generated: output/${filename}`);
    }
}
