import fs from 'fs';
import path from 'path';
import { format } from 'date-fns';
import { marked } from 'marked';
import { LinkedInPost } from './collector';
import { config } from './config';

import * as googleTTS from 'google-tts-api';

export class Generator {
    async createNewsletter(summary: string, posts: LinkedInPost[], dateRange?: { start: string, end: string }) {
        // Determine date string for filename and title
        let dateStr = format(new Date(), 'yyyy-MM-dd');
        let titleDateStr = dateStr;

        if (dateRange) {
            dateStr = `${dateRange.start}_to_${dateRange.end}`;
            titleDateStr = `${dateRange.start} to ${dateRange.end}`;
        }

        const outputPath = path.join(process.cwd(), 'output');

        if (!fs.existsSync(outputPath)) {
            fs.mkdirSync(outputPath);
        }

        if (config.OUTPUT_FORMAT === 'html') {
            await this.generateHTML(dateStr, titleDateStr, summary, posts, outputPath);
        } else {
            this.generateMarkdown(dateStr, titleDateStr, summary, posts, outputPath);
        }

        if (config.GENERATE_AUDIO) {
            await this.generateAudio(dateStr, summary, outputPath);
        }
    }

    private async generateAudio(dateStr: string, text: string, outputPath: string) {
        const filename = `newsletter_${dateStr}.mp3`;
        console.log('🔊 Generating Audio Overview...');

        try {
            // google-tts-api has a character limit (~200 chars), so we might need to split calls.
            // However, getAllAudioUrls or getAudioUrl might handle short texts.
            // For longer texts like summaries, we need to be careful.
            // Using getAllAudioBase64 provides an array of base64 strings we can join.

            // Clean markdown for better TTS
            const cleanText = text.replace(/[#*`]/g, '').replace(/\[(.*?)\]\(.*?\)/g, '$1');

            const audioBase64Array = await googleTTS.getAllAudioBase64(cleanText, {
                lang: 'en',
                slow: false,
                host: 'https://translate.google.com',
                timeout: 10000,
            });

            const combinedBase64 = audioBase64Array.map(item => item.base64).join('');
            const buffer = Buffer.from(combinedBase64, 'base64');

            fs.writeFileSync(path.join(outputPath, filename), buffer);
            console.log(`✅ Audio generated: output/${filename}`);
        } catch (error) {
            console.error('❌ Error generating audio:', error);
        }
    }

    private generateMarkdown(dateStr: string, titleDateStr: string, summary: string, posts: LinkedInPost[], outputPath: string) {
        const filename = `newsletter_${dateStr}.md`;
        const content = `
# AI LinkedIn Newsletter - ${titleDateStr}

${summary}

## Source Posts
${posts.map(p => `- [${p.title}](${p.link})\n  > ${p.snippet.replace(/\n/g, ' ')}`).join('\n')}

---
Generated by SocialMediaCollationforAI
`.trim();

        fs.writeFileSync(path.join(outputPath, filename), content);
        console.log(`✅ Newsletter generated (Markdown): output/${filename}`);
    }

    private async generateHTML(dateStr: string, titleDateStr: string, summary: string, posts: LinkedInPost[], outputPath: string) {
        const filename = `newsletter_${dateStr}.html`;
        const summaryHtml = await marked.parse(summary);

        const postsHtml = posts.map(p => `
            <div class="post">
                <h3><a href="${p.link}">${p.title}</a></h3>
                <p>${p.snippet.replace(/\n/g, ' ')}</p>
            </div>
        `).join('');

        const content = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Newsletter - ${titleDateStr}</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; line-height: 1.6; }
        h1 { color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 10px; }
        .post { margin-bottom: 20px; padding: 15px; background: #f8f9fa; border-radius: 8px; }
        .post h3 { margin-top: 0; }
        .post a { color: #0077b5; text-decoration: none; }
        .post a:hover { text-decoration: underline; }
        .footer { margin-top: 40px; font-size: 0.9em; color: #666; text-align: center; }
    </style>
</head>
<body>
    <h1>AI LinkedIn Newsletter - ${titleDateStr}</h1>
    
    <div class="summary">
        ${summaryHtml}
    </div>

    <h2>Source Posts</h2>
    ${postsHtml}

    <div class="footer">
        Generated by SocialMediaCollationforAI
    </div>
</body>
</html>
`;
        fs.writeFileSync(path.join(outputPath, filename), content);
        console.log(`✅ Newsletter generated (HTML): output/${filename}`);
    }
}
